version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api_test
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db:/var/lib/postgresql/data
